apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvprod001
  labels:
   nfs: server005
spec:
  capacity:             # 指定 PV 容量
    storage: 5Gi
  volumeMode: Filesystem  # 卷模式，除了文件系统，还支持原始块，Filesystem／Block
  accessModes: 
    - ReadWriteOnce   # 访问模式，ReadWriteOnce（该卷可以被单个节点以读/写模式挂载）， ReadOnlyMany（该卷可以被多个节点以只读模式挂载），ReadWriteMany（该卷可以被多个节点以读/写模式挂载
）
  persistentVolumeReclaimPolicy: Recycle  # 回收策略，Retain（保留，手动回收），Recycle（回收，基本擦除）， Delete（关联的存储资产（例如 AWS EBS、GCE PD、Azure Disk 和 OpenStack Cinder 
卷）将被删除）
  storageClassName: slow      # 存储类名。指定类名的 PV 需要与指定类名的 PVC 绑定
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: 10.1.222.176
